routes/web.php
<?php

use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::group(['middleware' => 'auth'], function(){
    Route::get('/', function () {
        return redirect('user');
    });
    
    Route::resource('user', UserController::class);
    Route::get('user/password/{id}', [UserController::class,'password'])->name('user.password');
    Route::put('user/change-password/{id}', [UserController::class,'changePassword'])->name('user.change.password');
    Route::get('/home', function ()
    {
        return redirect('user');
    })->name('home');
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function creator()
    {
        return $this->belongsTo(User::class,'created_by');
    }

    public function updater()
    {
        return $this->belongsTo(User::class,'updated_by');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    /**
     * 
     *
     * @param [type] $request
     * @param integer $action (1: create, 2: update, 3:delete)
     * @param boolean $is_success
     * @return void
     */
    public function alertMessage($request ,$action = 1,$is_success = true, $error_message = '')
    {
        # code...
        if($is_success == true){
            if($action == 1){
                $request->session()->flash('success',"Created record successfully!".$error_message);
            }
            else if($action == 2){
                $request->session()->flash('success',"Updated record successfully! ".$error_message);
            }
            else{
                $request->session()->flash('success',"Deleted record successfully! ".$error_message);

            }
        }
        else{
            if($action == 1){
                $request->session()->flash('error',"Creating record failed! ".$error_message);
            }
            else if($action == 2){
                $request->session()->flash('error',"Updating record failed! ".$error_message);
            }
            else{
                $request->session()->flash('error',"Deleting record failed! ".$error_message);
            }
        }
        
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\User\ChangePasswordRequest;
use App\Http\Requests\User\StoreRequest;
use App\Http\Requests\User\UpdateRequest;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datas = User::all();
            
            
        $title = 'User List';
        return view('user.index',compact('datas','title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title = 'Create User';

        return view('user.create',compact('title'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        $obj = new User();
        $obj->name = $request->name;
        $obj->email = $request->email;
        $obj->created_by = Auth::id();
        $obj->updated_by = Auth::id();
        $obj->password = bcrypt($request->password);
        
        $obj->save();

        $this->alertMessage($request,1,true);

        
        return redirect(route('user.show',$obj->id));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = User::whereId($id)->first();
        $creator = $data->creator;
        $updater = $data->updater;
        $title = 'User Detail';

        return view('user.show',compact('data','updater','creator','title'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = User::find($id);

        $title = 'Update User';

        return view('user.edit',compact('data','title'));
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        $user = User::findOrFail($id);

        $user->name = $request->name;
        $user->email = $request->email;
        $user->updated_by = Auth::id();
        $user->save();

        $this->alertMessage($request,2,true);
    
        return redirect(route('user.show',$user->id));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function password($id)
    {
        $data = User::findOrFail($id);
        $title = 'Change Password';
        return view('user.password',compact('data','title'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function changePassword(ChangePasswordRequest $request, $id)
    {
        $user = User::findOrFail($id);
        $user->password = bcrypt($request->password);
        $user->save();
        $this->alertMessage($request,2,true);
        return redirect('user');

    }
    

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        User::where('id',$request->id)->delete();
        $this->alertMessage($request,3,true);
        return response()->json([
             'status'=>'success'
        ],200);
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  @yield('title')

  <!-- Custom fonts for this template-->
  <link href="{{asset('template/vendor/fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="{{asset('template/css/sb-admin-2.min.css ')}}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    @yield('content')
  </div>


  <!-- Bootstrap core JavaScript-->
  <script src="{{asset('template/vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{asset('template/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{{asset('template/vendor/jquery-easing/jquery.easing.min.js')}}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{{asset('template/js/sb-admin-2.min.js')}}"></script>
  @yield('script')

</body>

</html>

resources/views/layouts/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{url('/')}}">
    {{-- <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div> --}}
    <div class="sidebar-brand-text mx-3">User Management
      {{-- <sup>2</sup> --}}
    </div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  
  <!-- Nav Item - Dashboard -->
  {{-- <li class="nav-item {{App\Helper\Helper::getActiveMenu('dashboard')}}">
    <a class="nav-link" href="{{url('dashboard')}}">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li> --}}

  <?php
      $case = array(
          'user.index',
          'user.create',
          'user.edit',
          'user.show',
      );
  ?>
  <!-- Nav Item - Dashboard -->
  <li class="nav-item {{App\Helper\Helper::getActiveMenu($case)}}">
    <a class="nav-link" href="{{route('user.index')}}">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>User</span></a>
  </li>



</ul>
<!-- End of Sidebar -->

resources/views/partials/css-plugin-for-table.blade.php
<!-- Custom styles for this page -->
<link href="{{asset('template/vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet">

resources/views/partials/js-plugin-for-table.blade.php
  <!-- Page level plugins -->
  <script src="{{asset('template/vendor/datatables/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('template/vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>

  <!-- Page level custom scripts -->
  <script src="{{asset('template/js/demo/datatables-demo.js')}}"></script>

resources/views/user/create.blade.php
@extends('layouts.master')
@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

      <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h5 mb-0 text-gray-800">Create User</h1>
        <a href="{{route('user.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm"><i class="fas fa-add"></i> Back</a>
      </div>
      <!-- DataTales Example -->
      <div class="card shadow mb-4">
        {{-- <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Create Case</h6>
        </div> --}}
        <div class="card-body">
          <div class="container" style="padding-top:10px;padding-bottom:10px">
            <div class=" col-md-12">
              <form class="form-horizontal" method="POST" action="{{route('user.store')}}">
                @csrf
                <div class="form-group row" >
                  <label class="control-label col-sm-2 form-label-text text-md-right text-lg-right text-xl-right" for="query_number">Name</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" value="{{old('name')}}" id="name" placeholder="Enter Name" name="name">
                    <span class="text-danger">{{ $errors->first('name') }}</span>
                  </div>
                </div>
                <div class="form-group row" >
                  <label class="control-label col-sm-2 form-label-text text-md-right text-lg-right text-xl-right" for="query_number">Email</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" value="{{old('email')}}" id="email" placeholder="Enter Email" name="email">
                    <span class="text-danger">{{ $errors->first('email') }}</span>
                  </div>
                </div>
                <div class="form-group row" >
                  <label class="control-label col-sm-2 form-label-text text-md-right text-lg-right text-xl-right" for="query_number">Password</label>
                  <div class="col-sm-10">
                    <input type="password" class="form-control"  id="password" placeholder="Enter Password" name="password">
                    <span class="text-danger">{{ $errors->first('password') }}</span>
                  </div>
                </div>
                <div class="form-group row" >
                  <label class="control-label col-sm-2 form-label-text text-md-right text-lg-right text-xl-right" for="query_number">Password Confirmation</label>
                  <div class="col-sm-10">
                    <input type="password" class="form-control"  id="password_confirmation" placeholder="Enter Password Confirmation" name="password_confirmation">
                    <span class="text-danger">{{ $errors->first('password_confirmation') }}</span>
                  </div>
                </div>
                <div class="form-group " style="text-align:end; padding-top:10px">
                    
                  <button type="submit" class="btn btn-primary btn-sm pull-right" > Save </button>
                </div>
              </form>
            </div> 
          </div>
        </div>
      </div>

      </div>
      <!-- /.container-fluid -->

@endsection

@section('script')


@endsection

resources/views/user/edit.blade.php
@extends('layouts.master')
@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

      <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h5 mb-0 text-gray-800">Update User</h1>
        <a href="{{route('user.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm"><i class="fas fa-add"></i> Back</a>
      </div>
      <!-- DataTales Example -->
      <div class="card shadow mb-4">
        {{-- <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Create Case</h6>
        </div> --}}
        <div class="card-body">
          <div class="container" style="padding-top:10px;padding-bottom:10px">
            <div class=" col-md-12">
              <form class="form-horizontal" method="POST" action="{{route('user.update',$data->id)}}">
                @csrf
                @method('PUT')
                <div class="form-group row" >
                  <label class="control-label col-sm-2 form-label-text text-md-right text-lg-right text-xl-right" for="query_number">Name</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" value="{{old('name')??$data->name}}" id="name" placeholder="Enter Name" name="name">
                    <span class="text-danger">{{ $errors->first('name') }}</span>
                  </div>
                </div>
                <div class="form-group row" >
                  <label class="control-label col-sm-2 form-label-text text-md-right text-lg-right text-xl-right" for="query_number">Email</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" value="{{old('email')??$data->email}}" id="email" placeholder="Enter Email" name="email">
                    <span class="text-danger">{{ $errors->first('email') }}</span>
                  </div>
                </div>
                {{-- <div class="form-group row" >
                  <label class="control-label col-sm-2 form-label-text text-md-right text-lg-right text-xl-right" for="query_number">Password</label>
                  <div class="col-sm-10">
                    <input type="password" class="form-control" value="{{old('password')??$data->password}}"  id="password" placeholder="Enter Password" name="password">
                    <span class="text-danger">{{ $errors->first('password') }}</span>
                  </div>
                </div>
                <div class="form-group row" >
                  <label class="control-label col-sm-2 form-label-text text-md-right text-lg-right text-xl-right" for="query_number">Password Confirmation</label>
                  <div class="col-sm-10">
                    <input type="password" class="form-control"  value="{{old('password_confirmation')??$data->password}}" id="password_confirmation" placeholder="Enter Password Confirmation" name="password_confirmation">
                    <span class="text-danger">{{ $errors->first('password_confirmation') }}</span>
                  </div>
                </div> --}}
                <div class="form-group " style="text-align:end; padding-top:10px">
                    
                  <button type="submit" class="btn btn-primary btn-sm pull-right" > Save </button>
                </div>
              </form>
            </div> 
          </div>
        </div>
      </div>

      </div>
      <!-- /.container-fluid -->

@endsection

resources/views/user/index.blade.php
@extends('layouts.master')
@section('style')
  @include('partials.css-plugin-for-table')

@endsection
@section('content')
    <!-- Begin Page Content -->
    
    <div class="container-fluid">
        
        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h5 mb-0 text-gray-800">User List</h1>
          <div >

            <a href="{{route('user.create')}}" class="btn btn-sm btn-primary "><i class="fas fa-add"></i> Create New</a>

          </div>
        </div>
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
          {{-- <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
          </div> --}}
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <td >&numero;</td>
                    <th style="width:12%">Name</th>
                    <th>Email</th>
                    <th style="width:185px">Created At</th>
                    <th style="width:185px">Updated At</th>
                    <th style="text-align:center; width:100px">Actions</th>

                  </tr>
                </thead>
                
                <tbody>
                  @php
                      $page = 0;
                      if(Request::get('page'))
                        $page  = Request::get('page')-1;
                      
                      $index = $page*20 + 1;
                  @endphp
                  @foreach ($datas as $key => $item)
                    <tr>
                      <td>{{$key + $index}}</td>
                      <td>{{$item->name}}</td>
                      <td>{{$item->email}}</td>
                      <td>{{$item->created_at}}</td>
                      <td>{{$item->updated_at}}</td>
                      <td align="center">
                        <a href="{{route('user.edit',$item->id)}}">
                          <i class="fas fa-edit"></i>
                        </a>
                        <a href="#" data-toggle="modal" data_id="{{$item->id}}" data-target="#modal-delete" onclick="onClickDelete('user/destroy',{{$item->id}})">
                          <i class="fas fa-trash"></i>
                        </a>
                        <a href="{{route('user.show',$item->id)}}">
                          <i class="fas fa-eye"></i>
                        </a>
                        <a href="{{route('user.password',$item->id)}}">
                          <i class="fas fa-key"></i>
                        </a>
                      </td>

                    </tr>
                  @endforeach
                  
                </tbody>
              </table>
            </div>
            {{-- {{$datas->appends(request()->except('page'))->links()}} --}}
          </div>
        </div>

    </div>
      <!-- /.container-fluid -->
@endsection

@section('script')
    @include('partials.js-plugin-for-table')

@endsection

resources/views/user/password.blade.php
@extends('layouts.master')
@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

      <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h5 mb-0 text-gray-800">Update User</h1>
        <a href="{{route('user.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm"><i class="fas fa-add"></i> Back</a>
      </div>
      <!-- DataTales Example -->
      <div class="card shadow mb-4">
        {{-- <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Create Case</h6>
        </div> --}}
        <div class="card-body">
          <div class="container" style="padding-top:10px;padding-bottom:10px">
            <div class=" col-md-12">
              <form class="form-horizontal" method="POST" action="{{route('user.change.password',$data->id)}}">
                @csrf
                @method('PUT')
                
                <div class="form-group row" >
                  <label class="control-label col-sm-2 form-label-text text-md-right text-lg-right text-xl-right" for="query_number">Password</label>
                  <div class="col-sm-10">
                    <input type="password" class="form-control"  id="password" placeholder="Enter Password" name="password">
                    <span class="text-danger">{{ $errors->first('password') }}</span>
                  </div>
                </div>
                <div class="form-group row" >
                  <label class="control-label col-sm-2 form-label-text text-md-right text-lg-right text-xl-right" for="query_number">Password Confirmation</label>
                  <div class="col-sm-10">
                    <input type="password" class="form-control"   id="password_confirmation" placeholder="Enter Password Confirmation" name="password_confirmation">
                    <span class="text-danger">{{ $errors->first('password_confirmation') }}</span>
                  </div>
                </div>
                <div class="form-group " style="text-align:end; padding-top:10px">
                    
                  <button type="submit" class="btn btn-primary btn-sm pull-right" > Save </button>
                </div>
              </form>
            </div> 
          </div>
        </div>
      </div>

      </div>
      <!-- /.container-fluid -->

@endsection

resources/views/user/show.blade.php
@extends('layouts.master')
@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

      <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h5 mb-0 text-gray-800"> User Details </h1>
        <div>
          <a href="{{route('user.edit',@$data->id)}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-add"></i> Update</a>
          <a href="{{route('user.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm"><i class="fas fa-add"></i> Back</a>

        </div>
      </div>
      <!-- DataTales Example -->
      <div class="card shadow mb-4">
        {{-- <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Create Case</h6>
        </div> --}}
        <div class="card-body">
          <div class="container" style="padding-top:10px;padding-bottom:10px">
            <div class="form-group row" >
              <label class="control-label col-sm-2 " for="query_number" ><b>Name</b></label>
              <div class="col-sm-10">
                <p>{{$data->name}}</p>
              </div>
            </div>
            <div class="form-group row" >
              <label class="control-label col-sm-2 " for="query_number" ><b>Phone</b></label>
              <div class="col-sm-10">
                <p>{{$data->email}}</p>
              </div>
            </div>
            <div class="form-group row" >
              <label class="control-label col-sm-2 " for="query_number" ><b>Created By</b></label>
              <div class="col-sm-10">
                <p>{{@$creator->name??'N/A'}}</p>
              </div>
            </div>
            <div class="form-group row" >
              <label class="control-label col-sm-2 " for="query_number" ><b>Updated By</b></label>
              <div class="col-sm-10">
                <p>{{@$updater->name??'N/A'}}</p>
              </div>
            </div>
            <div class="form-group row" >
              <label class="control-label col-sm-2 " for="query_number" ><b>Created At</b></label>
              <div class="col-sm-10">
                <p>{{$data->created_at}}</p>
              </div>
            </div>
            <div class="form-group row" >
              <label class="control-label col-sm-2 " for="query_number" ><b>Updated At</b></label>
              <div class="col-sm-10">
                <p>{{$data->updated_at}}</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      </div>
      <!-- /.container-fluid -->

@endsection